version: '3.1'

services:
  sql_server:
    container_name: SQL
    build: 
      context: .
      target: SQL
    ports:
      - 20000:1433
    volumes:
      - ./file_db/SQLServer/:/var/opt/mssql/data/
    restart: always
  
